<a href="https://colab.research.google.com/github/Keerthi0520/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard-/blob/main/python_Ecommerce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Code for Ecommersce Transaction Dataset

In [3]:
import pandas as pd
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Number of rows
num_rows = 10

# Create dataset with exactly 10 columns
data = {
    'TransactionID': np.arange(1001, 1001 + num_rows),
    'CustomerID': np.random.randint(101, 150, num_rows),
    'ProductID': np.random.randint(2001, 2050, num_rows),
    'Quantity': np.random.randint(1, 5, num_rows),
    'Price': np.round(np.random.uniform(10.0, 500.0, num_rows), 2),
    'TransactionDate': pd.date_range(start='2023-01-01', periods=num_rows),
    'PaymentMethod': np.random.choice(['Credit Card', 'Debit Card', 'UPI', 'PayPal'], num_rows),
    'ShippingAddress': [f'Address {i}' for i in range(1, num_rows + 1)],
    'OrderStatus': np.random.choice(['Delivered', 'Pending', 'Cancelled'], num_rows),
    'Category': np.random.choice(['Electronics', 'Books', 'Clothing', 'Home Appliances'], num_rows)
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the dataset
display(df)

# Print dataset shape
print("Dataset Shape:", df.shape)

,TransactionID,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,ShippingAddress,OrderStatus,Category
0,1001,139,2011,2,13.46,2023-01-01,PayPal,Address 1,Pending,Home Appliances
1,1002,129,2024,2,21.30,2023-01-02,PayPal,Address 2,Delivered,Clothing
2,1003,115,2036,2,267.14,2023-01-03,Credit Card,Address 3,Pending,Home Appliances
3,1004,143,2040,4,205.93,2023-01-04,UPI,Address 4,Pending,Electronics
4,1005,108,2024,4,32.87,2023-01-05,Credit Card,Address 5,Pending,Home Appliances
5,1006,121,2003,1,487.14,2023-01-06,UPI,Address 6,Delivered,Clothing
6,1007,139,2022,1,124.06,2023-01-07,UPI,Address 7,Pending,Clothing
7,1008,119,2002,4,54.40,2023-01-08,Credit Card,Address 8,Delivered,Books
8,1009,123,2024,2,313.01,2023-01-09,Credit Card,Address 9,Pending,Electronics
9,1010,111,2044,2,197.41,2023-01-10,UPI,Address 10,Cancelled,Home Appliances

Dataset Shape: (10, 10)

In [5]:
# Display the first 5 rows
df.head()

,TransactionID,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,ShippingAddress,OrderStatus,Category
0,1001,139,2011,2,13.46,2023-01-01,PayPal,Address 1,Pending,Home Appliances
1,1002,129,2024,2,21.30,2023-01-02,PayPal,Address 2,Delivered,Clothing
2,1003,115,2036,2,267.14,2023-01-03,Credit Card,Address 3,Pending,Home Appliances
3,1004,143,2040,4,205.93,2023-01-04,UPI,Address 4,Pending,Electronics
4,1005,108,2024,4,32.87,2023-01-05,Credit Card,Address 5,Pending,Home Appliances

In [7]:
# Display the last 5 rows
df.tail()

,TransactionID,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,ShippingAddress,OrderStatus,Category
5,1006,121,2003,1,487.14,2023-01-06,UPI,Address 6,Delivered,Clothing
6,1007,139,2022,1,124.06,2023-01-07,UPI,Address 7,Pending,Clothing
7,1008,119,2002,4,54.40,2023-01-08,Credit Card,Address 8,Delivered,Books
8,1009,123,2024,2,313.01,2023-01-09,Credit Card,Address 9,Pending,Electronics
9,1010,111,2044,2,197.41,2023-01-10,UPI,Address 10,Cancelled,Home Appliances

In [9]:
# Display general information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   CustomerID       10 non-null     int64
 2   ProductID        10 non-null     int64
 3   Quantity         10 non-null     int64
 4   Price            10 non-null     float64
 5   TransactionDate  10 non-null     datetime64[ns]
 6   PaymentMethod    10 non-null     object
 7   ShippingAddress  10 non-null     object
 8   OrderStatus      10 non-null     object
 9   Category         10 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(4), object(4)
memory usage: 932.0+ bytes

In [11]:
# Display data types of each column
df.dtypes

TransactionID               int64
CustomerID                  int64
ProductID                   int64
Quantity                    int64
Price                     float64
TransactionDate    datetime64[ns]
PaymentMethod              object
ShippingAddress            object
OrderStatus                object
Category                   object
dtype: object

In [13]:
# Display unique payment methods
df['PaymentMethod'].unique()

array(['PayPal', 'Credit Card', 'UPI'], dtype=object)

In [14]:
# Check for missing values
df.isnull().sum()

TransactionID      0
CustomerID         0
ProductID          0
Quantity           0
Price              0
TransactionDate    0
PaymentMethod      0
ShippingAddress    0
OrderStatus        0
Category           0
dtype: int64