<a href="https://colab.research.google.com/github/Keerthi0520/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard-/blob/main/Sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import sqlite3
import pandas as pd

# Create a NEW database
conn = sqlite3.connect("FoodDelivery_New.db")
cursor = conn.cursor()

In [28]:
cursor.execute("""
CREATE TABLE FoodDelivery (
    OrderID INTEGER PRIMARY KEY,
    CustomerName TEXT,
    RestaurantName TEXT,
    FoodItem TEXT,
    Quantity INTEGER,
    Price REAL,
    PaymentMethod TEXT,
    DeliveryPartner TEXT,
    OrderStatus TEXT,
    OrderDate TEXT
)
""")

conn.commit()
print("Table created successfully.")

Table created successfully.

In [29]:
cursor.executemany("""
INSERT INTO FoodDelivery
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""", [

(1001,'Rahul','Biryani House','Chicken Biryani',2,580.00,'UPI','Ravi','Delivered','2025-07-01'),

(1002,'Sneha','Pizza Hub','Veg Pizza',1,349.00,'Credit Card','Kiran','Delivered','2025-07-01'),

(1003,'Arjun','Burger Point','Cheese Burger',3,450.00,'Cash','Suresh','Pending','2025-07-02'),

(1004,'Priya','South Kitchen','Masala Dosa',2,240.00,'UPI','Ajay','Delivered','2025-07-02'),

(1005,'Anil','Chinese Wok','Fried Rice',1,220.00,'Debit Card','Ramesh','Cancelled','2025-07-03'),

(1006,'Divya','Tandoori Treat','Paneer Tikka',2,520.00,'UPI','Mahesh','Delivered','2025-07-03'),

(1007,'Karthik','Cafe Coffee','Cold Coffee',2,300.00,'Credit Card','Naresh','Delivered','2025-07-04'),

(1008,'Pooja','Sweet Magic','Gulab Jamun',4,280.00,'Cash','Vijay','Pending','2025-07-04'),

(1009,'Vikas','Andhra Spice','Meals',1,180.00,'UPI','Prakash','Delivered','2025-07-05'),

(1010,'Meena','Roll Express','Chicken Roll',2,260.00,'Debit Card','Santosh','Delivered','2025-07-05')

])

conn.commit()
print("10 records inserted successfully.")

10 records inserted successfully.

In [30]:
df = pd.read_sql_query("SELECT * FROM FoodDelivery;", conn)
display(df)

,OrderID,CustomerName,RestaurantName,FoodItem,Quantity,Price,PaymentMethod,DeliveryPartner,OrderStatus,OrderDate
0,1001,Rahul,Biryani House,Chicken Biryani,2,580.0,UPI,Ravi,Delivered,2025-07-01
1,1002,Sneha,Pizza Hub,Veg Pizza,1,349.0,Credit Card,Kiran,Delivered,2025-07-01
2,1003,Arjun,Burger Point,Cheese Burger,3,450.0,Cash,Suresh,Pending,2025-07-02
3,1004,Priya,South Kitchen,Masala Dosa,2,240.0,UPI,Ajay,Delivered,2025-07-02
4,1005,Anil,Chinese Wok,Fried Rice,1,220.0,Debit Card,Ramesh,Cancelled,2025-07-03
5,1006,Divya,Tandoori Treat,Paneer Tikka,2,520.0,UPI,Mahesh,Delivered,2025-07-03
6,1007,Karthik,Cafe Coffee,Cold Coffee,2,300.0,Credit Card,Naresh,Delivered,2025-07-04
7,1008,Pooja,Sweet Magic,Gulab Jamun,4,280.0,Cash,Vijay,Pending,2025-07-04
8,1009,Vikas,Andhra Spice,Meals,1,180.0,UPI,Prakash,Delivered,2025-07-05
9,1010,Meena,Roll Express,Chicken Roll,2,260.0,Debit Card,Santosh,Delivered,2025-07-05

In [31]:
pd.read_sql_query("SELECT * FROM FoodDelivery;", conn)

,OrderID,CustomerName,RestaurantName,FoodItem,Quantity,Price,PaymentMethod,DeliveryPartner,OrderStatus,OrderDate
0,1001,Rahul,Biryani House,Chicken Biryani,2,580.0,UPI,Ravi,Delivered,2025-07-01
1,1002,Sneha,Pizza Hub,Veg Pizza,1,349.0,Credit Card,Kiran,Delivered,2025-07-01
2,1003,Arjun,Burger Point,Cheese Burger,3,450.0,Cash,Suresh,Pending,2025-07-02
3,1004,Priya,South Kitchen,Masala Dosa,2,240.0,UPI,Ajay,Delivered,2025-07-02
4,1005,Anil,Chinese Wok,Fried Rice,1,220.0,Debit Card,Ramesh,Cancelled,2025-07-03
5,1006,Divya,Tandoori Treat,Paneer Tikka,2,520.0,UPI,Mahesh,Delivered,2025-07-03
6,1007,Karthik,Cafe Coffee,Cold Coffee,2,300.0,Credit Card,Naresh,Delivered,2025-07-04
7,1008,Pooja,Sweet Magic,Gulab Jamun,4,280.0,Cash,Vijay,Pending,2025-07-04
8,1009,Vikas,Andhra Spice,Meals,1,180.0,UPI,Prakash,Delivered,2025-07-05
9,1010,Meena,Roll Express,Chicken Roll,2,260.0,Debit Card,Santosh,Delivered,2025-07-05

In [23]:
pd.read_sql_query(
    "SELECT * FROM FoodDelivery WHERE OrderStatus='Delivered';",
    conn
)

,OrderID,CustomerName,RestaurantName,FoodItem,Quantity,Price,PaymentMethod,DeliveryPartner,OrderStatus,OrderDate
0,1001,Rahul,Biryani House,Chicken Biryani,2,580.0,UPI,Ravi,Delivered,2025-07-01
1,1002,Sneha,Pizza Hub,Veg Pizza,1,349.0,Credit Card,Kiran,Delivered,2025-07-01
2,1004,Priya,South Kitchen,Masala Dosa,2,240.0,UPI,Ajay,Delivered,2025-07-02
3,1006,Divya,Tandoori Treat,Paneer Tikka,2,520.0,UPI,Mahesh,Delivered,2025-07-03
4,1007,Karthik,Cafe Coffee,Cold Coffee,2,300.0,Credit Card,Naresh,Delivered,2025-07-04
5,1009,Vikas,Andhra Spice,Meals,1,180.0,UPI,Prakash,Delivered,2025-07-05
6,1010,Meena,Roll Express,Chicken Roll,2,260.0,Debit Card,Santosh,Delivered,2025-07-05

In [32]:
pd.read_sql_query(
    "SELECT AVG(Price) AS AveragePrice FROM FoodDelivery;",
    conn
)

   AveragePrice
0         337.9